# Generated by Django 2.1.7 on 2019-02-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000, verbose_name='Answer the question')),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Farmer's firstname")),
                ('last_name', models.CharField(max_length=50, verbose_name="Farmer's surname")),
                ('password', models.CharField(max_length=50, verbose_name="Farmer's password")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('zip_code', models.IntegerField(verbose_name='Zip code')),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AN', 'Animals'), ('PE', 'Pest Control'), ('SU', 'Purchase Suggestions'), ('SE', 'Seeds Types')], max_length=2)),
                ('question', models.TextField(max_length=1000, verbose_name='Ask a question')),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Farmer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Farmer'),
        ),
    ]
