# Generated by Django 2.1.7 on 2019-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=100, verbose_name="Farmer's password"),
        ),
    ]
