# Generated by Django 2.1.7 on 2019-02-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190226_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_by', to='forum.Farmer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_by', to='forum.Farmer'),
        ),
    ]
