# Generated by Django 2.1.7 on 2019-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190226_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AN', 'Animals'), ('PE', 'Pest Control'), ('SU', 'Purchase Suggestions'), ('SE', 'Seeds Types')], default='PE', max_length=2),
        ),
    ]
