# Generated by Django 2.1.7 on 2019-02-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190226_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='answer_upvoted_by', to='forum.Farmer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='forum.Farmer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='question_upvoted_by', to='forum.Farmer'),
        ),
    ]
