# Generated by Django 2.1.7 on 2019-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190226_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AN', 'Animals'), ('PE', 'Pest Control'), ('SU', 'Purchase'), ('SE', 'Seeds Types')], default='PE', max_length=2),
        ),
    ]
