# Generated by Django 2.1.7 on 2019-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
