# Generated by Django 2.1.7 on 2019-03-03 08:51

from django.db import migrations, models
import forum.file_paths
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20190303_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_file', models.FileField(upload_to=forum.file_paths.question_file_path, validators=[forum.validators.validate_file_extension], verbose_name='Question file')),
            ],
        ),
    ]
