# Generated by Django 2.1.7 on 2019-03-03 20:23

from django.db import migrations, models
import forum.file_paths
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_questionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='प्रश्न का उत्तर दें'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='dob',
            field=models.DateField(verbose_name='जन्म की तारीख'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='किसान का पहला नाम'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='किसान का उपनाम'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=100, verbose_name='किसान का पासवर्ड'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='फ़ोन नंबर'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='zip_code',
            field=models.IntegerField(verbose_name='पिन कोड'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AN', 'जानवर'), ('PE', 'Pest'), ('SU', 'खरीद सुझाव'), ('SE', 'Seeds')], default='PE', max_length=2, verbose_name='वर्ग'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='प्रश्न पूछें'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='question_file',
            field=models.FileField(upload_to=forum.file_paths.question_file_path, validators=[forum.validators.validate_file_extension], verbose_name='प्रश्न की फाइल'),
        ),
    ]
