# Generated by Django 2.1.7 on 2019-03-04 09:43

from django.db import migrations, models
import forum.file_paths
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190304_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.ManyToManyField(blank=True, to='forum.QuestionFile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AN', 'जानवर'), ('PE', 'कीट'), ('SU', 'खरीद सुझाव'), ('SE', 'खेत')], default='PE', max_length=2, verbose_name='वर्ग'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='question_file',
            field=models.FileField(upload_to=forum.file_paths.question_file_path, validators=[forum.validators.validate_file_extension, forum.validators.validate_file_size], verbose_name='प्रश्न की फाइल'),
        ),
    ]
