# Generated by Django 2.1.7 on 2019-03-13 06:18

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20190304_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[forum.validators.validate_phone_number], verbose_name='फ़ोन नंबर'),
        ),
    ]
