# Generated by Django 2.1.7 on 2019-03-20 08:11

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190313_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='zip_code',
            field=models.IntegerField(validators=[forum.validators.validate_zip_code], verbose_name='पिन कोड'),
        ),
    ]
