# Generated by Django 2.1.7 on 2019-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20190320_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='63d262f8-4827-4dba-9', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
