# Generated by Django 2.1.7 on 2019-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20190327_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='0627643d-8237-4c58-a', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
