# Generated by Django 2.1.7 on 2019-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20190329_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='ab2846c0-4457-4507-9', max_length=20),
        ),
    ]
