# Generated by Django 2.1.7 on 2019-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20190330_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='8530a6d6-45c9-4964-9', max_length=20),
        ),
    ]
