# Generated by Django 2.1.7 on 2019-04-09 14:35

from django.db import migrations, models
import forum.file_paths
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20190330_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='Answer the question'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='c05486de-b415-4b4f-a', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='dob',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Farmer's firstname"),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name="Farmer's surname"),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=100, verbose_name="Farmer's password"),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='zip_code',
            field=models.IntegerField(validators=[forum.validators.validate_zip_code], verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('AN', 'Animals'), ('PE', 'Pests'), ('SU', 'Purchase'), ('SE', 'Crop')], default='PE', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Ask a question'),
        ),
        migrations.AlterField(
            model_name='questionfile',
            name='question_file',
            field=models.FileField(upload_to=forum.file_paths.question_file_path, validators=[forum.validators.validate_file_extension, forum.validators.validate_file_size], verbose_name='Question file'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[forum.validators.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
