# Generated by Django 2.1.9 on 2019-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20190409_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='8423be90-a228-41df-a', max_length=20),
        ),
    ]
