# Generated by Django 2.1.7 on 2019-06-03 19:21

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20190604_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='farmer',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name="Farmer's name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='e9e81801-75b2-4bd4-a', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='zip_code',
            field=models.IntegerField(blank=True, validators=[forum.validators.validate_zip_code], verbose_name='पिन कोड'),
        ),
    ]
