# Generated by Django 2.1.7 on 2019-06-06 18:07

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20190604_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='account_token',
            field=models.CharField(blank=True, default='06fe6121-a44e-4649-a', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, validators=[forum.validators.validate_zip_code], verbose_name='पिन कोड'),
        ),
    ]
