# Generated by Django 6.0.1 on 2026-01-11 14:07

from django.db import migrations
from django.contrib.auth.hashers import make_password
from datetime import datetime
import random


def create_dummy_data(apps, schema_editor):
    """Create dummy farmers, questions, answers, and specialists"""

    Farmer = apps.get_model('forum', 'Farmer')
    Question = apps.get_model('forum', 'Question')
    Answer = apps.get_model('forum', 'Answer')
    Specialist = apps.get_model('forum', 'Specialist')

    # Create 5 dummy farmers with fictional names
    farmers_data = [
        {
            'first_name': 'John',
            'last_name': 'Farmer',
            'phone_number': '0000000000',
            'dob': datetime(1980, 5, 15).date(),
            'zip_code': 462001,
            'password': make_password('hello1234'),
        },
        {
            'first_name': 'Alice',
            'last_name': 'Greenfield',
            'phone_number': '0000000001',
            'dob': datetime(1985, 8, 22).date(),
            'zip_code': 462003,
            'password': make_password('hello1234'),
        },
        {
            'first_name': 'Bob',
            'last_name': 'Harvest',
            'phone_number': '0000000002',
            'dob': datetime(1975, 3, 10).date(),
            'zip_code': 462005,
            'password': make_password('hello1234'),
        },
        {
            'first_name': 'Carol',
            'last_name': 'Meadows',
            'phone_number': '0000000003',
            'dob': datetime(1990, 11, 5).date(),
            'zip_code': 462008,
            'password': make_password('hello1234'),
        },
        {
            'first_name': 'Dave',
            'last_name': 'Cropwell',
            'phone_number': '0000000004',
            'dob': datetime(1982, 7, 18).date(),
            'zip_code': 462010,
            'password': make_password('hello1234'),
        },
    ]

    farmers = []
    for farmer_data in farmers_data:
        farmer = Farmer.objects.create(**farmer_data)
        farmers.append(farmer)

    print(f"Created {len(farmers)} dummy farmers")

    # Create dummy specialists
    specialists_data = [
        {
            'name': 'Dr. Emma Soilwise',
            'phone_number': '1111111111',
            'subject': 'Soil Science',
        },
        {
            'name': 'Dr. Frank Pestman',
            'phone_number': '1111111112',
            'subject': 'Pest Control',
        },
        {
            'name': 'Dr. Grace Vetcare',
            'phone_number': '1111111113',
            'subject': 'Animal Health',
        },
        {
            'name': 'Prof. Henry Seedling',
            'phone_number': '1111111114',
            'subject': 'Crop Management',
        },
        {
            'name': 'Dr. Iris Waterwise',
            'phone_number': '1111111115',
            'subject': 'Irrigation',
        },
    ]

    specialists = []
    for specialist_data in specialists_data:
        specialist = Specialist.objects.create(**specialist_data)
        specialists.append(specialist)

    print(f"Created {len(specialists)} dummy specialists")

    # Create dummy questions from different farmers
    questions_data = [
        {
            'asked_by': farmers[0],
            'category': 'PE',
            'question': 'My wheat crop has small brown spots on the leaves. What could be causing this and how do I treat it?',
        },
        {
            'asked_by': farmers[0],
            'category': 'SE',
            'question': 'What is the best time to sow rice in Madhya Pradesh? Should I wait for monsoon or start earlier?',
        },
        {
            'asked_by': farmers[1],
            'category': 'AN',
            'question': 'My cow is not eating properly for the last 2 days. She seems weak. What should I do?',
        },
        {
            'asked_by': farmers[1],
            'category': 'SU',
            'question': 'Where can I buy good quality fertilizer at reasonable price in Dabra area?',
        },
        {
            'asked_by': farmers[2],
            'category': 'PE',
            'question': 'How to control aphids in mustard crop? They are spreading very fast.',
        },
        {
            'asked_by': farmers[2],
            'category': 'SE',
            'question': 'Which vegetables are most profitable to grow in summer season?',
        },
        {
            'asked_by': farmers[3],
            'category': 'AN',
            'question': 'What vaccinations are necessary for buffalo calves? When should they be given?',
        },
        {
            'asked_by': farmers[3],
            'category': 'SU',
            'question': 'Looking for recommendations for a good quality water pump for irrigation. Budget is around 15000 rupees.',
        },
        {
            'asked_by': farmers[4],
            'category': 'SE',
            'question': 'My tomato plants are getting yellow leaves from bottom. Is this normal or disease?',
        },
        {
            'asked_by': farmers[4],
            'category': 'PE',
            'question': 'White flies on cotton plants. What organic methods can control them?',
        },
    ]

    questions = []
    for question_data in questions_data:
        question = Question.objects.create(**question_data)
        questions.append(question)

    print(f"Created {len(questions)} dummy questions")

    # Add upvotes to questions (random farmers upvote random questions)
    for question in questions:
        # Randomly select 1-3 farmers to upvote each question
        num_upvoters = random.randint(1, 3)
        upvoters = random.sample(farmers, num_upvoters)
        for farmer in upvoters:
            if farmer != question.asked_by:  # Don't let farmers upvote their own questions
                question.upvoted_by.add(farmer)

    print("Added upvotes to questions")

    # Create dummy answers for each question
    answers_data = [
        # Answers for question 0 (wheat brown spots)
        {
            'answer_of': questions[0],
            'answered_by': farmers[2],
            'answer': 'This could be leaf rust disease. Spray Propiconazole fungicide mixed with water. Also remove affected leaves and burn them. Make sure there is proper spacing between plants for air circulation.',
        },
        {
            'answer_of': questions[0],
            'answered_by': farmers[3],
            'answer': 'I had same problem last year. Use Mancozeb spray twice with 7 days gap. Also reduce water if you are overwatering.',
        },

        # Answers for question 1 (rice sowing time)
        {
            'answer_of': questions[1],
            'answered_by': farmers[1],
            'answer': 'Best time for rice sowing in MP is June to early July. Wait for good monsoon rains. Soil should have enough moisture before transplanting.',
        },

        # Answers for question 2 (cow not eating)
        {
            'answer_of': questions[2],
            'answered_by': farmers[0],
            'answer': 'This could be serious. Check her temperature first. If she has fever, call veterinary doctor immediately. Meanwhile give her jaggery mixed in warm water.',
        },
        {
            'answer_of': questions[2],
            'answered_by': farmers[4],
            'answer': 'Don\'t delay. Sometimes animals get stomach problems from eating plastic or rotten food. Vet doctor can give proper treatment after examination.',
        },

        # Answers for question 3 (fertilizer purchase)
        {
            'answer_of': questions[3],
            'answered_by': farmers[4],
            'answer': 'You can check with Krishi Upaj Mandi in Dabra. They have authorized dealers. Also compare prices with nearby cooperative society.',
        },

        # Answers for question 4 (aphids in mustard)
        {
            'answer_of': questions[4],
            'answered_by': farmers[1],
            'answer': 'Use Imidacloprid insecticide spray. Mix 1ml in 1 liter water and spray in evening time. Repeat after 10 days if needed.',
        },
        {
            'answer_of': questions[4],
            'answered_by': farmers[3],
            'answer': 'For organic method, spray neem oil solution. Mix 5ml neem oil + 1ml liquid soap in 1 liter water. Spray every 5 days.',
        },

        # Answers for question 5 (summer vegetables)
        {
            'answer_of': questions[5],
            'answered_by': farmers[0],
            'answer': 'Bottle gourd, bitter gourd, and okra (bhindi) are good for summer. They give good yield and fetch good price in market. Make sure you have drip irrigation for water saving.',
        },

        # Answers for question 6 (buffalo vaccinations)
        {
            'answer_of': questions[6],
            'answered_by': farmers[2],
            'answer': 'FMD (Foot and Mouth Disease) vaccine at 4 months age. HS (Hemorrhagic Septicemia) at 6 months. Consult nearest veterinary hospital for exact schedule.',
        },

        # Answers for question 7 (water pump)
        {
            'answer_of': questions[7],
            'answered_by': farmers[1],
            'answer': 'For 15000 budget, you can get 1 HP submersible pump. Check brands like Kirloskar, Crompton or CRI. Make sure to check warranty.',
        },

        # Answers for question 8 (tomato yellow leaves)
        {
            'answer_of': questions[8],
            'answered_by': farmers[2],
            'answer': 'Yellow bottom leaves can be normal aging or nitrogen deficiency. Apply urea fertilizer - 1 tablespoon per plant. Also check if soil drainage is proper.',
        },
        {
            'answer_of': questions[8],
            'answered_by': farmers[4],
            'answer': 'Could also be overwatering. Tomato plants don\'t like wet feet. Water only when top soil is dry. Remove yellow leaves.',
        },

        # Answers for question 9 (white flies on cotton)
        {
            'answer_of': questions[9],
            'answered_by': farmers[0],
            'answer': 'Spray yellow sticky traps around plants to catch white flies. For organic control, use soap water spray (2 tablespoon soap in 1 liter water).',
        },
    ]

    answers = []
    for answer_data in answers_data:
        answer = Answer.objects.create(**answer_data)
        answers.append(answer)

    print(f"Created {len(answers)} dummy answers")

    # Add upvotes to answers (random farmers upvote random answers)
    for answer in answers:
        # Randomly select 0-2 farmers to upvote each answer
        num_upvoters = random.randint(0, 2)
        if num_upvoters > 0:
            upvoters = random.sample(farmers, num_upvoters)
            for farmer in upvoters:
                if farmer != answer.answered_by:  # Don't let farmers upvote their own answers
                    answer.upvoted_by.add(farmer)

    print("Added upvotes to answers")
    print("Dummy data creation completed successfully!")


def remove_dummy_data(apps, schema_editor):
    """Remove all dummy data (reverse migration)"""

    Farmer = apps.get_model('forum', 'Farmer')
    Specialist = apps.get_model('forum', 'Specialist')
    Question = apps.get_model('forum', 'Question')
    Answer = apps.get_model('forum', 'Answer')

    # Delete dummy farmers by phone numbers
    # This will cascade delete all questions and answers because of ForeignKey on_delete=CASCADE
    dummy_farmer_phone_numbers = [
        '0000000000', '0000000001', '0000000002',
        '0000000003', '0000000004'
    ]
    
    deleted_farmers = Farmer.objects.filter(phone_number__in=dummy_farmer_phone_numbers).delete()
    print(f"Deleted farmers and related data: {deleted_farmers}")

    # Delete dummy specialists by phone numbers
    dummy_specialist_phone_numbers = [
        '1111111111', '1111111112', '1111111113',
        '1111111114', '1111111115'
    ]
    
    deleted_specialists = Specialist.objects.filter(phone_number__in=dummy_specialist_phone_numbers).delete()
    print(f"Deleted specialists: {deleted_specialists}")

    print("Removed all dummy data successfully!")


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20201128_1625'),
    ]

    operations = [
        migrations.RunPython(create_dummy_data, remove_dummy_data),
    ]