"""
Django settings for Farmer project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import django_heroku
import os
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
production = config("PROD") == "True"
DEBUG = not production

ALLOWED_HOSTS_FROM_ENV = config("ALLOWED_HOSTS")
PROD_ALLOWED_HOSTS = ALLOWED_HOSTS_FROM_ENV.split(
    ",") if ALLOWED_HOSTS_FROM_ENV else []
ALLOWED_HOSTS = PROD_ALLOWED_HOSTS if production else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Added apps

    'forum.apps.ForumConfig',
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # added middlewares

    'htmlmin.middleware.HtmlMinifyMiddleware',
    'htmlmin.middleware.MarkRequestMiddleware',

]

ROOT_URLCONF = 'Farmer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Farmer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'hi'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale")
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),

]

# PWA Configuration
PWA_APP_NAME = 'Pucho Kisan'
PWA_APP_DESCRIPTION = "Farming questions and answers platform"
PWA_APP_THEME_COLOR = '#1565C0'  # Change to your brand color
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {
        'src': '/static/forum/images/icons/icon-72x72.png',
        'sizes': '72x72'
    },
    {
        'src': '/static/forum/images/icons/icon-96x96.png',
        'sizes': '96x96'
    },
    {
        'src': '/static/forum/images/icons/icon-128x128.png',
        'sizes': '128x128'
    },
    {
        'src': '/static/forum/images/icons/icon-144x144.png',
        'sizes': '144x144'
    },
    {
        'src': '/static/forum/images/icons/icon-152x152.png',
        'sizes': '152x152'
    },
    {
        'src': '/static/forum/images/icons/icon-192x192.png',
        'sizes': '192x192'
    },
    {
        'src': '/static/forum/images/icons/icon-384x384.png',
        'sizes': '384x384'
    },
    {
        'src': '/static/forum/images/icons/icon-512x512.png',
        'sizes': '512x512'
    }
]

PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/forum/images/icons/icon-152x152.png',
        'sizes': '152x152'
    }
]

PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

# Point to your existing service worker
PWA_SERVICE_WORKER_PATH = os.path.join(
    BASE_DIR,
    'forum/static/forum/js',
    'serviceworker.js'
)

# Activate Django-Heroku.
django_heroku.settings(locals())


# Minification Turned on

HTML_MINIFY = True
